package com.v2soft.training.model;
// Generated Oct 9, 2019, 1:39:32 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * EmployeeAddress generated by hbm2java
 */
@Entity
@Table(name = "employee_address", catalog = "employee")
public class EmployeeAddress implements java.io.Serializable {

	private EmployeeAddressId id;
	private AddressType addressType;
	private Employee employeeinfo;
	private String addressLine1;
	private String addressLine2;
	private String city;
	private String state;
	private String zipCode;
	private String zip4;

	public EmployeeAddress() {
	}

	public EmployeeAddress(EmployeeAddressId id, AddressType addressType, Employee employeeinfo,
			String addressLine1, String city, String state, String zipCode) {
		this.id = id;
		this.addressType = addressType;
		this.employeeinfo = employeeinfo;
		this.addressLine1 = addressLine1;
		this.city = city;
		this.state = state;
		this.zipCode = zipCode;
	}

	public EmployeeAddress(EmployeeAddressId id, AddressType addressType, Employee employeeinfo,
			String addressLine1, String addressLine2, String city, String state, String zipCode, String zip4) {
		this.id = id;
		this.addressType = addressType;
		this.employeeinfo = employeeinfo;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.city = city;
		this.state = state;
		this.zipCode = zipCode;
		this.zip4 = zip4;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "employeeId", column = @Column(name = "Employee_id", nullable = false, length = 12)),
			@AttributeOverride(name = "addressTypeId", column = @Column(name = "Address_Type_Id", nullable = false)) })
	public EmployeeAddressId getId() {
		return this.id;
	}

	public void setId(EmployeeAddressId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Address_Type_Id", nullable = false, insertable = false, updatable = false)
	public AddressType getAddressType() {
		return this.addressType;
	}

	public void setAddressType(AddressType addressType) {
		this.addressType = addressType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Employee_id", nullable = false, insertable = false, updatable = false)
	public Employee getEmployeeinfo() {
		return this.employeeinfo;
	}

	public void setEmployeeinfo(Employee employeeinfo) {
		this.employeeinfo = employeeinfo;
	}

	@Column(name = "Address_Line1", nullable = false, length = 50)
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "Address_Line2", length = 50)
	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@Column(name = "City", nullable = false, length = 50)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "State", nullable = false, length = 50)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "ZipCode", nullable = false, length = 10)
	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	@Column(name = "Zip4", length = 4)
	public String getZip4() {
		return this.zip4;
	}

	public void setZip4(String zip4) {
		this.zip4 = zip4;
	}

}
