package com.v2soft.training.model;

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LoginSession generated by hbm2java
 */
@Entity
@Table(name = "login_session", catalog = "employee")
public class LoginSession implements java.io.Serializable {

	private LoginSessionId id;
	private EmployeeLogin login;
	private String createdBy;
	private Date createdTime;
	private String updatedBy;
	private Date updatedTime;
	private Date loginTime;
	private Date logoutTime;
	private String status;

	public LoginSession() {
	}

	public LoginSession(LoginSessionId id, EmployeeLogin login, String createdBy, Date createdTime, String updatedBy,
			Date loginTime, String status) {
		this.id = id;
		this.login = login;
		this.createdBy = createdBy;
		this.createdTime = createdTime;
		this.updatedBy = updatedBy;
		this.loginTime = loginTime;
		this.status = status;
	}

	public LoginSession(LoginSessionId id, EmployeeLogin login, String createdBy, Date createdTime, String updatedBy,
			Date updatedTime, Date loginTime, Date logoutTime, String status) {
		this.id = id;
		this.login = login;
		this.createdBy = createdBy;
		this.createdTime = createdTime;
		this.updatedBy = updatedBy;
		this.updatedTime = updatedTime;
		this.loginTime = loginTime;
		this.logoutTime = logoutTime;
		this.status = status;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "loginSessionId", column = @Column(name = "login_session_id", nullable = false, length = 100)),
			@AttributeOverride(name = "userName", column = @Column(name = "userName", nullable = false, length = 20)),
			@AttributeOverride(name = "employeeId", column = @Column(name = "Employee_id", nullable = false, length = 12)) })
	public LoginSessionId getId() {
		return this.id;
	}

	public void setId(LoginSessionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "userName", referencedColumnName = "userName", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "Employee_id", referencedColumnName = "Employee_id", nullable = false, insertable = false, updatable = false) })
	public EmployeeLogin getLogin() {
		return this.login;
	}

	public void setLogin(EmployeeLogin login) {
		this.login = login;
	}

	@Column(name = "created_by", nullable = false, length = 30)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time", nullable = false, length = 19)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "updated_by", nullable = false, length = 30)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_time", length = 19)
	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "login_time", nullable = false, length = 19)
	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "logout_time", length = 19)
	public Date getLogoutTime() {
		return this.logoutTime;
	}

	public void setLogoutTime(Date logoutTime) {
		this.logoutTime = logoutTime;
	}

	@Column(name = "status", nullable = false, length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}

