package com.v2soft.training.dataModel;
// Generated Oct 9, 2019, 1:39:32 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employeeinfo generated by hbm2java
 */
public class EmployeeMod implements java.io.Serializable {

	private String employeeId;
	private Date dateOfBirth;
	private String firstName;
	private String lastName;
	private String middleName;
	private String passportNumber;
	private String ssn;
	private Set<EmployeeLoginMod> employeeLogins = new HashSet<EmployeeLoginMod>(0);
	private Set<EmployeeAddressMod> employeeAddresses = new HashSet<EmployeeAddressMod>(0);

	public EmployeeMod() {
	}

	public EmployeeMod(String employeeId, Date dateOfBirth, String firstName, String lastName, String ssn) {
		this.employeeId = employeeId;
		this.dateOfBirth = dateOfBirth;
		this.firstName = firstName;
		this.lastName = lastName;
		this.ssn = ssn;
	}

	public EmployeeMod(String employeeId, Date dateOfBirth, String firstName, String lastName, String middleName,
			String passportNumber, String ssn, Set<EmployeeLoginMod> employeeLogins,
			Set<EmployeeAddressMod> employeeAddresses) {
		this.employeeId = employeeId;
		this.dateOfBirth = dateOfBirth;
		this.firstName = firstName;
		this.lastName = lastName;
		this.middleName = middleName;
		this.passportNumber = passportNumber;
		this.ssn = ssn;
		this.employeeLogins = employeeLogins;
		this.employeeAddresses = employeeAddresses;
	}

	public String getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public String getPassportNumber() {
		return this.passportNumber;
	}

	public void setPassportNumber(String passportNumber) {
		this.passportNumber = passportNumber;
	}

	public String getSsn() {
		return this.ssn;
	}

	public void setSsn(String ssn) {
		this.ssn = ssn;
	}

	public Set<EmployeeLoginMod> getEmployeeLogins() {
		return this.employeeLogins;
	}

	public void setEmployeeLogins(Set<EmployeeLoginMod> employeeLogins) {
		this.employeeLogins = employeeLogins;
	}

	public Set<EmployeeAddressMod> getEmployeeAddresses() {
		return this.employeeAddresses;
	}

	public void setEmployeeAddresses(Set<EmployeeAddressMod> employeeAddresses) {
		this.employeeAddresses = employeeAddresses;
	}
}
