package com.v2soft.training.dataModel;

import java.util.HashSet;
import java.util.Set;

/**
 * Login generated by hbm2java
 */
public class EmployeeLoginMod implements java.io.Serializable {

	private EmployeeLoginIdMod id;
	private EmployeeMod employeeinfo;
	private String password;
	private Set<LoginSessionMod> loginSessions = new HashSet<LoginSessionMod>(0);

	public EmployeeLoginMod() {
	}

	public EmployeeLoginMod(EmployeeLoginIdMod id, EmployeeMod employeeinfo, String password) {
		this.id = id;
		this.employeeinfo = employeeinfo;
		this.password = password;
	}

	public EmployeeLoginMod(EmployeeLoginIdMod id, EmployeeMod employeeinfo, String password, Set<LoginSessionMod> loginSessions) {
		this.id = id;
		this.employeeinfo = employeeinfo;
		this.password = password;
		this.loginSessions = loginSessions;
	}

	public EmployeeLoginIdMod getId() {
		return this.id;
	}

	public void setId(EmployeeLoginIdMod id) {
		this.id = id;
	}

	public EmployeeMod getEmployeeinfo() {
		return this.employeeinfo;
	}

	public void setEmployeeinfo(EmployeeMod employeeinfo) {
		this.employeeinfo = employeeinfo;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set<LoginSessionMod> getLoginSessions() {
		return this.loginSessions;
	}

	public void setLoginSessions(Set<LoginSessionMod> loginSessions) {
		this.loginSessions = loginSessions;
	}

}

