package com.v2soft.training.dataModel;
// Generated Oct 9, 2019, 1:39:32 PM by Hibernate Tools 5.1.10.Final

/**
 * EmployeeAddress generated by hbm2java
 */
public class EmployeeAddressMod implements java.io.Serializable {

	private EmployeeAddressIdMod id;
	private AddressTypeMod addressType;
	private EmployeeMod employeeInfo;
	private String addressLineOne;
	private String addressLineTwo;
	private String city;
	private String state;
	private String zipcode;
	private String zipfour;

	public EmployeeAddressMod() {
	}

	public EmployeeAddressMod(EmployeeAddressIdMod id, AddressTypeMod addressType, EmployeeMod employeeInfo,
			String addressLineOne, String city, String state, String zipcode) {
		this.id = id;
		this.addressType = addressType;
		this.employeeInfo = employeeInfo;
		this.addressLineOne = addressLineOne;
		this.city = city;
		this.state = state;
		this.zipcode = zipcode;
	}

	public EmployeeAddressMod(EmployeeAddressIdMod id, AddressTypeMod addressType, EmployeeMod employeeInfo,
			String addressLineOne, String addressLineTwo, String city, String state, String zipcode, String zipfour) {
		this.id = id;
		this.addressType = addressType;
		this.employeeInfo = employeeInfo;
		this.addressLineOne = addressLineOne;
		this.addressLineTwo = addressLineTwo;
		this.city = city;
		this.state = state;
		this.zipcode = zipcode;
		this.zipfour = zipfour;
	}

	public EmployeeAddressIdMod getId() {
		return this.id;
	}

	public void setId(EmployeeAddressIdMod id) {
		this.id = id;
	}

	public AddressTypeMod getAddressType() {
		return this.addressType;
	}

	public void setAddressType(AddressTypeMod addressType) {
		this.addressType = addressType;
	}

	public EmployeeMod getEmployeeInfo() {
		return this.employeeInfo;
	}

	public void setEmployeeInfo(EmployeeMod employeeInfo) {
		this.employeeInfo = employeeInfo;
	}

	public String getAddressLineOne() {
		return this.addressLineOne;
	}

	public void setAddressLineOne(String addressLineOne) {
		this.addressLineOne = addressLineOne;
	}

	public String getAddressLineTwo() {
		return this.addressLineTwo;
	}

	public void setAddressLineTwo(String addressLineTwo) {
		this.addressLineTwo = addressLineTwo;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public String getZipfour() {
		return this.zipfour;
	}

	public void setZipfour(String zipfour) {
		this.zipfour = zipfour;
	}

}
