package com.v2soft.training.dataModel;

import java.util.Date;

/**
 * LoginSession generated by hbm2java
 */
public class LoginSessionMod implements java.io.Serializable {

	private LoginSessionIdMod id;
	private EmployeeLoginMod login;
	private String createdBy;
	private Date createdTime;
	private String updatedBy;
	private Date updatedTime;
	private Date loginTime;
	private Date logoutTime;
	private String status;

	public LoginSessionMod() {
	}

	public LoginSessionMod(LoginSessionIdMod id, EmployeeLoginMod login, String createdBy, Date createdTime, String updatedBy,
			Date loginTime, String status) {
		this.id = id;
		this.login = login;
		this.createdBy = createdBy;
		this.createdTime = createdTime;
		this.updatedBy = updatedBy;
		this.loginTime = loginTime;
		this.status = status;
	}

	public LoginSessionMod(LoginSessionIdMod id, EmployeeLoginMod login, String createdBy, Date createdTime, String updatedBy,
			Date updatedTime, Date loginTime, Date logoutTime, String status) {
		this.id = id;
		this.login = login;
		this.createdBy = createdBy;
		this.createdTime = createdTime;
		this.updatedBy = updatedBy;
		this.updatedTime = updatedTime;
		this.loginTime = loginTime;
		this.logoutTime = logoutTime;
		this.status = status;
	}

	public LoginSessionIdMod getId() {
		return this.id;
	}

	public void setId(LoginSessionIdMod id) {
		this.id = id;
	}

	public EmployeeLoginMod getLogin() {
		return this.login;
	}

	public void setLogin(EmployeeLoginMod login) {
		this.login = login;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	public Date getLogoutTime() {
		return this.logoutTime;
	}

	public void setLogoutTime(Date logoutTime) {
		this.logoutTime = logoutTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}

