package com.v2soft.training.dataModel;

/**
 * LoginSessionId generated by hbm2java
 */
public class LoginSessionIdMod implements java.io.Serializable {

	private String loginSessionId;
	private String userName;
	private String employeeId;

	public LoginSessionIdMod() {
	}

	public LoginSessionIdMod(String loginSessionId, String userName, String employeeId) {
		this.loginSessionId = loginSessionId;
		this.userName = userName;
		this.employeeId = employeeId;
	}

	public String getLoginSessionId() {
		return this.loginSessionId;
	}

	public void setLoginSessionId(String loginSessionId) {
		this.loginSessionId = loginSessionId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LoginSessionIdMod))
			return false;
		LoginSessionIdMod castOther = (LoginSessionIdMod) other;

		return ((this.getLoginSessionId() == castOther.getLoginSessionId())
				|| (this.getLoginSessionId() != null && castOther.getLoginSessionId() != null
						&& this.getLoginSessionId().equals(castOther.getLoginSessionId())))
				&& ((this.getUserName() == castOther.getUserName()) || (this.getUserName() != null
						&& castOther.getUserName() != null && this.getUserName().equals(castOther.getUserName())))
				&& ((this.getEmployeeId() == castOther.getEmployeeId())
						|| (this.getEmployeeId() != null && castOther.getEmployeeId() != null
								&& this.getEmployeeId().equals(castOther.getEmployeeId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLoginSessionId() == null ? 0 : this.getLoginSessionId().hashCode());
		result = 37 * result + (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result + (getEmployeeId() == null ? 0 : this.getEmployeeId().hashCode());
		return result;
	}

}
